[package]
name = "wasm-exports"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.79" }

fractal-simulations = {path = "../fractal-simulations"}